### ISSUE TITLE
How to get user-dependent values into view model?

### ISSUE THREAD

**Issue by ghost** [JonPSmith/EfCore.GenericBizRunner#14]
Hi Jon,

trying out ``EfCore.GenericBizRunner`` I ran into following challenge:

I have a table with many products owned by different users.
The view should allow users to edit their own products, while others can only be viewed.
An administrator shall be able to edit all products.
I am using ASP.NET Core authentication.

For example. consider your ``ExampleWebApp`` and look at ``Home\\Index.cshtml`` around line 61:

    @foreach (var item in Model.BooksList) { ... }

I'd like to have a property ``item.CanEditBook`` which is ``true`` for admins and for the author of the current book. How would I do that? Any ideas? Or would you say, that `ServiceLayer.BookServices.BookListDto` should not contain user-dependent values and the view should generate user-dependent content on its own?

Thanks!

**Comment by JonPSmith** [comment]
HI @LukeOwlclaw,

This isn't something the `EfCore.GenericBizRunner` library can help as its a security issue rather than a business rule. I am familiar with this sort of problem as I work on [multi-tenant applications](https://github.com/JonPSmith/AuthPermissions.AspNetCore). I'm sure there are a few solutions to your issue, but I will suggest one that I would use with EF Core.

I would:

1. Add a parameter to the `Product` entity class which holds the owner, e.g. `Product.Owner = "Company name"`. 
2. Add a table that links the `Owner` to each logged in user, e.g. table containing the user's Email and the name of their company. 
3. In your edit code you would check the `Owner` value linked to current user against the `Product.Owner` value in the `Product` entity class and reject an edit.
   - Typically you also filter the products (in the service layer) that the user can edit, which is a more helpful display. e.g. `context.Products.Where(x => loggedInUser.Owner == null ||  loggedInUser.Owner == x.Owner)...` (NOTE: The null test allows the admin to see all products).

In my multi-tenant library I add a security/filter claim to the user on login, but that's just improves performance.
