### ISSUE TITLE
Option to use this library with ServiceLifetime.Transient

### ISSUE THREAD

**Issue by S0PEX** [JonPSmith/EfCore.GenericBizRunner#9]
Hey,

I am currently migrating my project to GraphQl instead of the rest pattern.
Therefore I need to set the service lifetime of the context to ```ServiceLifetime.Transient```. Because in GraphQl each field of the request is called concurrently so that if the lifetime is set to ```ServiceLifetime.Scoped``` which will when fail because the same context is used by two different resolvers. Is there a simple workaround to get ```IActionServiceAsync``` working with a transient context because else the runner doesn't call ```SaveChanges()``` on the correct context instance.

Regards Artur

**Comment by JonPSmith** [comment]
Hi @S0PEX,

~~I looked at the code and you can't replace the `RegisterBizRunnerWithDtoScans` method with your own because it call internal classes. BUT, if you use `RegisterGenericBizRunnerMultiDbContext` it doesn't define the DbContext, but uses the provided Class/Interface when you create the IActionService/Async - see this in the [Using multiple DbContexts docs](https://github.com/JonPSmith/EfCore.GenericBizRunner/wiki/Using-multiple-DbContexts). This makes your creation of the IActionService I little bit longer to write, but gives you the control you need.~~

Sorry, I thought the problem though and it won't work. That's because `GenericBizRunner` will call `SaveChanges` on a different instance to the one that the your business logic uses. That measn no data will be saved.

Sorry, `GenericBizRunner` can't run with a DbContext which is Transient.

**Comment by JonPSmith** [comment]
See updated response.
